//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateFw.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ModulesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModulesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TemplateFw.Resources.Resources.ModulesResource", typeof(ModulesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Faq {
            get {
                return ResourceManager.GetString("Faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإجابة.
        /// </summary>
        internal static string Faq_Answer {
            get {
                return ResourceManager.GetString("Faq_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإجابة باللغة العربية.
        /// </summary>
        internal static string Faq_AnswerAr {
            get {
                return ResourceManager.GetString("Faq_AnswerAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإجابة باللغة الانجليزية.
        /// </summary>
        internal static string Faq_AnswerEn {
            get {
                return ResourceManager.GetString("Faq_AnswerEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات السؤال.
        /// </summary>
        internal static string Faq_Info {
            get {
                return ResourceManager.GetString("Faq_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادارة الأسئلة الشائعة.
        /// </summary>
        internal static string Faq_Management {
            get {
                return ResourceManager.GetString("Faq_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البوابة.
        /// </summary>
        internal static string Faq_Portal {
            get {
                return ResourceManager.GetString("Faq_Portal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر البوابة.
        /// </summary>
        internal static string Faq_PortalChoose {
            get {
                return ResourceManager.GetString("Faq_PortalChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال.
        /// </summary>
        internal static string Faq_Question {
            get {
                return ResourceManager.GetString("Faq_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال باللغة العربية.
        /// </summary>
        internal static string Faq_QuestionAr {
            get {
                return ResourceManager.GetString("Faq_QuestionAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال باللغة الانجليزية.
        /// </summary>
        internal static string Faq_QuestionEn {
            get {
                return ResourceManager.GetString("Faq_QuestionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخدمة.
        /// </summary>
        internal static string Faq_Service {
            get {
                return ResourceManager.GetString("Faq_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الخدمة.
        /// </summary>
        internal static string Faq_ServiceChoose {
            get {
                return ResourceManager.GetString("Faq_ServiceChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأسئلة الشائعة.
        /// </summary>
        internal static string Faqs {
            get {
                return ResourceManager.GetString("Faqs", resourceCulture);
            }
        }
    }
}
