//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateFw.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModulesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModulesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TemplateFw.Resources.Resources.ModulesResources", typeof(ModulesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البلدان.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البلد.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرمز.
        /// </summary>
        public static string Country_Code {
            get {
                return ResourceManager.GetString("Country_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إنشاؤه بواسطة.
        /// </summary>
        public static string Country_CreatedBy {
            get {
                return ResourceManager.GetString("Country_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإنشاء.
        /// </summary>
        public static string Country_CreationDate {
            get {
                return ResourceManager.GetString("Country_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات الدولة.
        /// </summary>
        public static string Country_Information {
            get {
                return ResourceManager.GetString("Country_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متاح؟.
        /// </summary>
        public static string Country_IsAvailable {
            get {
                return ResourceManager.GetString("Country_IsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ آخر تعديل.
        /// </summary>
        public static string Country_LastModificationDate {
            get {
                return ResourceManager.GetString("Country_LastModificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخر تعديل بواسطة.
        /// </summary>
        public static string Country_LastModifiedBy {
            get {
                return ResourceManager.GetString("Country_LastModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة الدول.
        /// </summary>
        public static string Country_Management {
            get {
                return ResourceManager.GetString("Country_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string Country_Name {
            get {
                return ResourceManager.GetString("Country_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإسم باللغة العربية.
        /// </summary>
        public static string Country_NameAr {
            get {
                return ResourceManager.GetString("Country_NameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإسم باللغة الانجليزية.
        /// </summary>
        public static string Country_NameEn {
            get {
                return ResourceManager.GetString("Country_NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأسئلة الشائعة.
        /// </summary>
        public static string Faq {
            get {
                return ResourceManager.GetString("Faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاجابة.
        /// </summary>
        public static string Faq_Answer {
            get {
                return ResourceManager.GetString("Faq_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجواب باللغة العربية.
        /// </summary>
        public static string Faq_AnswerAr {
            get {
                return ResourceManager.GetString("Faq_AnswerAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجواب باللغة الإنجليزية.
        /// </summary>
        public static string Faq_AnswerEn {
            get {
                return ResourceManager.GetString("Faq_AnswerEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البوابة.
        /// </summary>
        public static string Faq_Portal {
            get {
                return ResourceManager.GetString("Faq_Portal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر البوابة.
        /// </summary>
        public static string Faq_PortalChoose {
            get {
                return ResourceManager.GetString("Faq_PortalChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال.
        /// </summary>
        public static string Faq_Question {
            get {
                return ResourceManager.GetString("Faq_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال باللغة العربية.
        /// </summary>
        public static string Faq_QuestionAr {
            get {
                return ResourceManager.GetString("Faq_QuestionAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال باللغة الإنجليزية.
        /// </summary>
        public static string Faq_QuestionEn {
            get {
                return ResourceManager.GetString("Faq_QuestionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخدمة.
        /// </summary>
        public static string Faq_Service {
            get {
                return ResourceManager.GetString("Faq_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الخدمة.
        /// </summary>
        public static string Faq_ServiceChoose {
            get {
                return ResourceManager.GetString("Faq_ServiceChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأسئلة الشائعة.
        /// </summary>
        public static string Faqs {
            get {
                return ResourceManager.GetString("Faqs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغة.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هو الافتراضي؟.
        /// </summary>
        public static string Language_IsDefault {
            get {
                return ResourceManager.GetString("Language_IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغات.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        public static string Portal_Description {
            get {
                return ResourceManager.GetString("Portal_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف باللغة العربية.
        /// </summary>
        public static string Portal_DescriptionAr {
            get {
                return ResourceManager.GetString("Portal_DescriptionAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف باللغة الإنجليزية.
        /// </summary>
        public static string Portal_DescriptionEn {
            get {
                return ResourceManager.GetString("Portal_DescriptionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرابط.
        /// </summary>
        public static string Portal_Link {
            get {
                return ResourceManager.GetString("Portal_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البوابات.
        /// </summary>
        public static string Portals {
            get {
                return ResourceManager.GetString("Portals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشروط.
        /// </summary>
        public static string Service_Conditions {
            get {
                return ResourceManager.GetString("Service_Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشروط باللغة العربية.
        /// </summary>
        public static string Service_ConditionsAr {
            get {
                return ResourceManager.GetString("Service_ConditionsAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشروط باللغة الإنجليزية.
        /// </summary>
        public static string Service_ConditionsEn {
            get {
                return ResourceManager.GetString("Service_ConditionsEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوثيقة المطلوبة.
        /// </summary>
        public static string Service_DocumentRequired {
            get {
                return ResourceManager.GetString("Service_DocumentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوثيقة المطلوبة باللغة العربية.
        /// </summary>
        public static string Service_DocumentRequiredAr {
            get {
                return ResourceManager.GetString("Service_DocumentRequiredAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوثيقة المطلوبة باللغة الإنجليزية.
        /// </summary>
        public static string Service_DocumentRequiredEn {
            get {
                return ResourceManager.GetString("Service_DocumentRequiredEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرسوم.
        /// </summary>
        public static string Service_Fees {
            get {
                return ResourceManager.GetString("Service_Fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرسوم باللغة العربية.
        /// </summary>
        public static string Service_FeesAr {
            get {
                return ResourceManager.GetString("Service_FeesAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرسوم باللغة الانجليزية.
        /// </summary>
        public static string Service_FeesEn {
            get {
                return ResourceManager.GetString("Service_FeesEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأيقونة.
        /// </summary>
        public static string Service_Icon {
            get {
                return ResourceManager.GetString("Service_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يتم نشر؟.
        /// </summary>
        public static string Service_IsPublished {
            get {
                return ResourceManager.GetString("Service_IsPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول مطلوب.
        /// </summary>
        public static string Service_LogInRequired {
            get {
                return ResourceManager.GetString("Service_LogInRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان url للجوال.
        /// </summary>
        public static string Service_MobileUrl {
            get {
                return ResourceManager.GetString("Service_MobileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملاحظات.
        /// </summary>
        public static string Service_Notes {
            get {
                return ResourceManager.GetString("Service_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملاحظات باللغة العربية.
        /// </summary>
        public static string Service_NotesAr {
            get {
                return ResourceManager.GetString("Service_NotesAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملاحظات باللغة الإنجليزية.
        /// </summary>
        public static string Service_NotesEn {
            get {
                return ResourceManager.GetString("Service_NotesEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف وسائط pdf.
        /// </summary>
        public static string Service_PdfMediaId {
            get {
                return ResourceManager.GetString("Service_PdfMediaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم النشر في.
        /// </summary>
        public static string Service_PublishedAt {
            get {
                return ResourceManager.GetString("Service_PublishedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم نشره بواسطة.
        /// </summary>
        public static string Service_PublishedBy {
            get {
                return ResourceManager.GetString("Service_PublishedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود الخدمة.
        /// </summary>
        public static string Service_ServiceCode {
            get {
                return ResourceManager.GetString("Service_ServiceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الخدمة.
        /// </summary>
        public static string Service_ServiceType {
            get {
                return ResourceManager.GetString("Service_ServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر نوع الخدمة.
        /// </summary>
        public static string Service_ServiceTypeChoose {
            get {
                return ResourceManager.GetString("Service_ServiceTypeChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف المختصر.
        /// </summary>
        public static string Service_ShortDescription {
            get {
                return ResourceManager.GetString("Service_ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف المختصر باللغة العربية.
        /// </summary>
        public static string Service_ShortDescriptionAr {
            get {
                return ResourceManager.GetString("Service_ShortDescriptionAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف المختصر باللغة الإنجليزية.
        /// </summary>
        public static string Service_ShortDescriptionEn {
            get {
                return ResourceManager.GetString("Service_ShortDescriptionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العرض في الأصول.
        /// </summary>
        public static string Service_ShowInAssets {
            get {
                return ResourceManager.GetString("Service_ShowInAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العرض في الكتالوج.
        /// </summary>
        public static string Service_ShowInCatalog {
            get {
                return ResourceManager.GetString("Service_ShowInCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العرض في متابعة.
        /// </summary>
        public static string Service_ShowInFollowUp {
            get {
                return ResourceManager.GetString("Service_ShowInFollowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخطوات.
        /// </summary>
        public static string Service_Steps {
            get {
                return ResourceManager.GetString("Service_Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخطوات باللغة العربية.
        /// </summary>
        public static string Service_StepsAr {
            get {
                return ResourceManager.GetString("Service_StepsAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخطوات باللغة الانجليزية.
        /// </summary>
        public static string Service_StepsEn {
            get {
                return ResourceManager.GetString("Service_StepsEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توقف عند.
        /// </summary>
        public static string Service_StoppedAt {
            get {
                return ResourceManager.GetString("Service_StoppedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توقف من قبل.
        /// </summary>
        public static string Service_StoppedBy {
            get {
                return ResourceManager.GetString("Service_StoppedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوقت المطلوب.
        /// </summary>
        public static string Service_TimeRequired {
            get {
                return ResourceManager.GetString("Service_TimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوقت المطلوب باللغة العربية.
        /// </summary>
        public static string Service_TimeRequiredAr {
            get {
                return ResourceManager.GetString("Service_TimeRequiredAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوقت المطلوب باللغة الإنجليزية.
        /// </summary>
        public static string Service_TimeRequiredEn {
            get {
                return ResourceManager.GetString("Service_TimeRequiredEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرابط.
        /// </summary>
        public static string Service_Url {
            get {
                return ResourceManager.GetString("Service_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفيديو.
        /// </summary>
        public static string Service_Video {
            get {
                return ResourceManager.GetString("Service_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتيب العرض.
        /// </summary>
        public static string Service_ViewOrder {
            get {
                return ResourceManager.GetString("Service_ViewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخدمات.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنواع الخدمة.
        /// </summary>
        public static string ServiceTypes {
            get {
                return ResourceManager.GetString("ServiceTypes", resourceCulture);
            }
        }
    }
}
