//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateFw.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OperationsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OperationsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TemplateFw.Resources.Resources.OperationsResources", typeof(OperationsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية الاضافة بنجاح.
        /// </summary>
        public static string OperationDone_1 {
            get {
                return ResourceManager.GetString("OperationDone_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية الحفظ بنجاح.
        /// </summary>
        public static string OperationDone_10 {
            get {
                return ResourceManager.GetString("OperationDone_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية الرفض بنجاح.
        /// </summary>
        public static string OperationDone_11 {
            get {
                return ResourceManager.GetString("OperationDone_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية الرد بنجاح.
        /// </summary>
        public static string OperationDone_12 {
            get {
                return ResourceManager.GetString("OperationDone_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية استدعاء البيانات بنجاح .
        /// </summary>
        public static string OperationDone_13 {
            get {
                return ResourceManager.GetString("OperationDone_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية استدعاء البيانات بنجاح .
        /// </summary>
        public static string OperationDone_14 {
            get {
                return ResourceManager.GetString("OperationDone_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية الرفع بنجاح .
        /// </summary>
        public static string OperationDone_15 {
            get {
                return ResourceManager.GetString("OperationDone_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية التحميل بنجاح .
        /// </summary>
        public static string OperationDone_16 {
            get {
                return ResourceManager.GetString("OperationDone_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية التحقق بنجاح.
        /// </summary>
        public static string OperationDone_17 {
            get {
                return ResourceManager.GetString("OperationDone_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية إرسال كود التحقق بنجاح.
        /// </summary>
        public static string OperationDone_18 {
            get {
                return ResourceManager.GetString("OperationDone_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية إرسال التسجيل بنجاح.
        /// </summary>
        public static string OperationDone_19 {
            get {
                return ResourceManager.GetString("OperationDone_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية استدعاء البيانات بنجاح .
        /// </summary>
        public static string OperationDone_2 {
            get {
                return ResourceManager.GetString("OperationDone_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية التعديل بنجاح.
        /// </summary>
        public static string OperationDone_3 {
            get {
                return ResourceManager.GetString("OperationDone_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية الحذف بنجاح.
        /// </summary>
        public static string OperationDone_4 {
            get {
                return ResourceManager.GetString("OperationDone_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية التفعيل بنجاح.
        /// </summary>
        public static string OperationDone_5 {
            get {
                return ResourceManager.GetString("OperationDone_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية الإيقاف بنجاح.
        /// </summary>
        public static string OperationDone_6 {
            get {
                return ResourceManager.GetString("OperationDone_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية النشر بنجاح.
        /// </summary>
        public static string OperationDone_7 {
            get {
                return ResourceManager.GetString("OperationDone_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية الإيقاف بنجاح.
        /// </summary>
        public static string OperationDone_8 {
            get {
                return ResourceManager.GetString("OperationDone_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية استدعاء البيانات بنجاح.
        /// </summary>
        public static string OperationDone_9 {
            get {
                return ResourceManager.GetString("OperationDone_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ.
        /// </summary>
        public static string OperationErrorTitle {
            get {
                return ResourceManager.GetString("OperationErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نأسف حدث خطأ غير متوقع.
        /// </summary>
        public static string OperationFailed_0 {
            get {
                return ResourceManager.GetString("OperationFailed_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية الاضافة.
        /// </summary>
        public static string OperationFailed_1 {
            get {
                return ResourceManager.GetString("OperationFailed_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية الحفظ.
        /// </summary>
        public static string OperationFailed_10 {
            get {
                return ResourceManager.GetString("OperationFailed_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية الرفض.
        /// </summary>
        public static string OperationFailed_11 {
            get {
                return ResourceManager.GetString("OperationFailed_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية الرد.
        /// </summary>
        public static string OperationFailed_12 {
            get {
                return ResourceManager.GetString("OperationFailed_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية استدعاء البيانات.
        /// </summary>
        public static string OperationFailed_13 {
            get {
                return ResourceManager.GetString("OperationFailed_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية استدعاء البيانات.
        /// </summary>
        public static string OperationFailed_14 {
            get {
                return ResourceManager.GetString("OperationFailed_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية الرفع.
        /// </summary>
        public static string OperationFailed_15 {
            get {
                return ResourceManager.GetString("OperationFailed_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية التحميل.
        /// </summary>
        public static string OperationFailed_16 {
            get {
                return ResourceManager.GetString("OperationFailed_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية التحقق.
        /// </summary>
        public static string OperationFailed_17 {
            get {
                return ResourceManager.GetString("OperationFailed_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية إرسال كود التحقق.
        /// </summary>
        public static string OperationFailed_18 {
            get {
                return ResourceManager.GetString("OperationFailed_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية التسجيل.
        /// </summary>
        public static string OperationFailed_19 {
            get {
                return ResourceManager.GetString("OperationFailed_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية استدعاء البيانات.
        /// </summary>
        public static string OperationFailed_2 {
            get {
                return ResourceManager.GetString("OperationFailed_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية التعديل.
        /// </summary>
        public static string OperationFailed_3 {
            get {
                return ResourceManager.GetString("OperationFailed_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية الحذف.
        /// </summary>
        public static string OperationFailed_4 {
            get {
                return ResourceManager.GetString("OperationFailed_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية التفعيل.
        /// </summary>
        public static string OperationFailed_5 {
            get {
                return ResourceManager.GetString("OperationFailed_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية الإيقاف.
        /// </summary>
        public static string OperationFailed_6 {
            get {
                return ResourceManager.GetString("OperationFailed_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية النشر.
        /// </summary>
        public static string OperationFailed_7 {
            get {
                return ResourceManager.GetString("OperationFailed_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية الإيقاف.
        /// </summary>
        public static string OperationFailed_8 {
            get {
                return ResourceManager.GetString("OperationFailed_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية استدعاء البيانات.
        /// </summary>
        public static string OperationFailed_9 {
            get {
                return ResourceManager.GetString("OperationFailed_9", resourceCulture);
            }
        }
    }
}
